# Generated by Django 5.0.6 on 2024-05-18 19:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scene", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scene",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
